version: '3'

services:

  db:
    image: "postgres:9.6-alpine"
    restart: always
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iboarici
    ports:
      - "5432:5432"

  recipe:
    build: ./recipe-application/.
    container_name: recipe-app
    ports:
      - "9091:9091"

  recipe-fe:
    build: ./recipe-app-fe/.
    container_name: recipe-fe
    ports:
      - "4200:80"

volumes:
  postgres-data: