version: '3.1'

services:
  db:
    image: "postgres:9.6-alpine"
    restart: always
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iboarici
    ports:
      - "5432:5432"

  recipe:
    build: .
    container_name: recipe-app
    ports:
      - "9091:9091"

volumes:
  postgres-data: