spring:
  application:
    name: recipe-app
  profiles:
    active: prod
---
server:
  port: 9091

spring:
  mvc:
    format:
      date: dd-MM-yyyy
      date-time: dd-MM-yyyy HH:mm
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
  sql:
    init:
      mode: always
      platform: dev
  config:
    activate:
      on-profile: dev
---
server:
  port: 9091

spring:
  mvc:
    format:
      date: dd-MM-yyyy
      date-time: dd-MM-yyyy HH:mm
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    #url: jdbc:postgresql://localhost:15432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: iboarici
    jpa.database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  sql:
    init:
      mode: always
      platform: prod
  config:
    activate:
      on-profile: prod
